server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /api/ {
        proxy_pass http://94.139.255.29:60444;
        rewrite ^/api(/.*)$ $1 break;
    }
}
